import type { Term } from './types';

/**
 * Preset terminology for each domain.
 * These are installed on first run and can be edited by the user afterwards.
 * IDs are fixed so that re-installs don't duplicate entries.
 * createdAt / updatedAt are set to 0 here and stamped with Date.now() on install.
 */

export const PRESET_TERMS_GENERAL: Term[] = [];

export const PRESET_TERMS_LEGAL: Term[] = [
  {
    id: 'preset-legal-001',
    domain: 'legal',
    translations: { en: 'consideration', zh: '对价', et: 'vastutasu', ja: '約因', fr: 'contrepartie', de: 'Gegenleistung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-002',
    domain: 'legal',
    translations: { en: 'jurisdiction', zh: '管辖权', et: 'jurisdiktsioon', ja: '管轄権', fr: 'juridiction', de: 'Gerichtsbarkeit' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-003',
    domain: 'legal',
    translations: { en: 'liability', zh: '责任', et: 'vastutus', ja: '責任', fr: 'responsabilité', de: 'Haftung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-004',
    domain: 'legal',
    translations: { en: 'plaintiff', zh: '原告', et: 'hageja', ja: '原告', fr: 'demandeur', de: 'Kläger' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-005',
    domain: 'legal',
    translations: { en: 'defendant', zh: '被告', et: 'kostja', ja: '被告', fr: 'défendeur', de: 'Beklagter' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-006',
    domain: 'legal',
    translations: { en: 'arbitration', zh: '仲裁', et: 'vahekohus', ja: '仲裁', fr: 'arbitrage', de: 'Schiedsverfahren' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-007',
    domain: 'legal',
    translations: { en: 'breach', zh: '违约', et: 'rikkumine', ja: '違反', fr: 'rupture', de: 'Vertragsbruch' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-008',
    domain: 'legal',
    translations: { en: 'contract', zh: '合同', et: 'leping', ja: '契約', fr: 'contrat', de: 'Vertrag' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-009',
    domain: 'legal',
    translations: { en: 'damages', zh: '损害赔偿', et: 'kahjuhüvitis', ja: '損害賠償', fr: 'dommages-intérêts', de: 'Schadensersatz' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-010',
    domain: 'legal',
    translations: { en: 'due diligence', zh: '尽职调查', et: 'hoolsuskohustus', ja: 'デューデリジェンス', fr: 'diligence raisonnable', de: 'Sorgfaltspflicht' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-011',
    domain: 'legal',
    translations: { en: 'indemnity', zh: '赔偿', et: 'hüvitis', ja: '補償', fr: 'indemnisation', de: 'Entschädigung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-012',
    domain: 'legal',
    translations: { en: 'injunction', zh: '禁令', et: 'ettekirjutus', ja: '差止命令', fr: 'injonction', de: 'einstweilige Verfügung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-013',
    domain: 'legal',
    translations: { en: 'litigation', zh: '诉讼', et: 'kohtuvaidlus', ja: '訴訟', fr: 'litige', de: 'Rechtsstreit' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-014',
    domain: 'legal',
    translations: { en: 'negligence', zh: '过失', et: 'hooletus', ja: '過失', fr: 'négligence', de: 'Fahrlässigkeit' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-015',
    domain: 'legal',
    translations: { en: 'notarize', zh: '公证', et: 'notariaalselt tõestama', ja: '公証する', fr: 'notarier', de: 'notariell beglaubigen' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-016',
    domain: 'legal',
    translations: { en: 'power of attorney', zh: '授权委托书', et: 'volikiri', ja: '委任状', fr: 'procuration', de: 'Vollmacht' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-017',
    domain: 'legal',
    translations: { en: 'precedent', zh: '判例', et: 'pretsedent', ja: '判例', fr: 'précédent', de: 'Präzedenzfall' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-018',
    domain: 'legal',
    translations: { en: 'settlement', zh: '和解', et: 'kokkulepe', ja: '和解', fr: 'règlement', de: 'Vergleich' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-019',
    domain: 'legal',
    translations: { en: 'statute', zh: '法规', et: 'seadus', ja: '法令', fr: 'loi', de: 'Gesetz' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-020',
    domain: 'legal',
    translations: { en: 'testimony', zh: '证词', et: 'tunnistus', ja: '証言', fr: 'témoignage', de: 'Aussage' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-021',
    domain: 'legal',
    translations: { en: 'tort', zh: '侵权', et: 'delikt', ja: '不法行為', fr: 'délit civil', de: 'unerlaubte Handlung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-022',
    domain: 'legal',
    translations: { en: 'warrant', zh: '令状', et: 'order', ja: '令状', fr: 'mandat', de: 'Haftbefehl' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-023',
    domain: 'legal',
    translations: { en: 'intellectual property', zh: '知识产权', et: 'intellektuaalomand', ja: '知的財産', fr: 'propriété intellectuelle', de: 'geistiges Eigentum' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-024',
    domain: 'legal',
    translations: { en: 'confidentiality', zh: '保密', et: 'konfidentsiaalsus', ja: '守秘義務', fr: 'confidentialité', de: 'Vertraulichkeit' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-legal-025',
    domain: 'legal',
    translations: { en: 'force majeure', zh: '不可抗力', et: 'vääramatu jõud', ja: '不可抗力', fr: 'force majeure', de: 'höhere Gewalt' },
    createdAt: 0,
    updatedAt: 0,
  },
];

export const PRESET_TERMS_MEDICAL: Term[] = [
  {
    id: 'preset-medical-001',
    domain: 'medical',
    translations: { en: 'diagnosis', zh: '诊断', et: 'diagnoos', ja: '診断', fr: 'diagnostic', de: 'Diagnose' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-002',
    domain: 'medical',
    translations: { en: 'prescription', zh: '处方', et: 'retsept', ja: '処方', fr: 'ordonnance', de: 'Rezept' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-003',
    domain: 'medical',
    translations: { en: 'symptom', zh: '症状', et: 'sümptom', ja: '症状', fr: 'symptôme', de: 'Symptom' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-004',
    domain: 'medical',
    translations: { en: 'prognosis', zh: '预后', et: 'prognoos', ja: '予後', fr: 'pronostic', de: 'Prognose' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-005',
    domain: 'medical',
    translations: { en: 'anesthesia', zh: '麻醉', et: 'anesteesia', ja: '麻酔', fr: 'anesthésie', de: 'Anästhesie' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-006',
    domain: 'medical',
    translations: { en: 'biopsy', zh: '活检', et: 'biopsia', ja: '生検', fr: 'biopsie', de: 'Biopsie' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-007',
    domain: 'medical',
    translations: { en: 'chronic', zh: '慢性', et: 'krooniline', ja: '慢性', fr: 'chronique', de: 'chronisch' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-008',
    domain: 'medical',
    translations: { en: 'acute', zh: '急性', et: 'äge', ja: '急性', fr: 'aigu', de: 'akut' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-009',
    domain: 'medical',
    translations: { en: 'inflammation', zh: '炎症', et: 'põletik', ja: '炎症', fr: 'inflammation', de: 'Entzündung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-010',
    domain: 'medical',
    translations: { en: 'tumor', zh: '肿瘤', et: 'kasvaja', ja: '腫瘍', fr: 'tumeur', de: 'Tumor' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-011',
    domain: 'medical',
    translations: { en: 'therapy', zh: '治疗', et: 'teraapia', ja: '治療', fr: 'thérapie', de: 'Therapie' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-012',
    domain: 'medical',
    translations: { en: 'surgery', zh: '手术', et: 'kirurgia', ja: '手術', fr: 'chirurgie', de: 'Chirurgie' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-013',
    domain: 'medical',
    translations: { en: 'vaccine', zh: '疫苗', et: 'vaktsiin', ja: 'ワクチン', fr: 'vaccin', de: 'Impfstoff' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-014',
    domain: 'medical',
    translations: { en: 'allergy', zh: '过敏', et: 'allergia', ja: 'アレルギー', fr: 'allergie', de: 'Allergie' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-015',
    domain: 'medical',
    translations: { en: 'antibiotic', zh: '抗生素', et: 'antibiootikum', ja: '抗生物質', fr: 'antibiotique', de: 'Antibiotikum' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-016',
    domain: 'medical',
    translations: { en: 'blood pressure', zh: '血压', et: 'vererõhk', ja: '血圧', fr: 'pression artérielle', de: 'Blutdruck' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-017',
    domain: 'medical',
    translations: { en: 'cholesterol', zh: '胆固醇', et: 'kolesterool', ja: 'コレステロール', fr: 'cholestérol', de: 'Cholesterin' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-018',
    domain: 'medical',
    translations: { en: 'diabetes', zh: '糖尿病', et: 'diabeet', ja: '糖尿病', fr: 'diabète', de: 'Diabetes' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-019',
    domain: 'medical',
    translations: { en: 'immune system', zh: '免疫系统', et: 'immuunsüsteem', ja: '免疫系', fr: 'système immunitaire', de: 'Immunsystem' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-020',
    domain: 'medical',
    translations: { en: 'infection', zh: '感染', et: 'infektsioon', ja: '感染', fr: 'infection', de: 'Infektion' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-021',
    domain: 'medical',
    translations: { en: 'malignant', zh: '恶性', et: 'pahaloomuline', ja: '悪性', fr: 'malin', de: 'bösartig' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-022',
    domain: 'medical',
    translations: { en: 'benign', zh: '良性', et: 'healoomuline', ja: '良性', fr: 'bénin', de: 'gutartig' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-023',
    domain: 'medical',
    translations: { en: 'metabolism', zh: '新陈代谢', et: 'ainevahetus', ja: '代謝', fr: 'métabolisme', de: 'Stoffwechsel' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-024',
    domain: 'medical',
    translations: { en: 'rehabilitation', zh: '康复', et: 'taastusravi', ja: 'リハビリテーション', fr: 'rééducation', de: 'Rehabilitation' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-medical-025',
    domain: 'medical',
    translations: { en: 'ultrasound', zh: '超声波', et: 'ultraheli', ja: '超音波', fr: 'échographie', de: 'Ultraschall' },
    createdAt: 0,
    updatedAt: 0,
  },
];

export const PRESET_TERMS_TECH: Term[] = [
  {
    id: 'preset-tech-001',
    domain: 'tech',
    translations: { en: 'API', zh: '接口', et: 'API', ja: 'API', fr: 'API', de: 'API' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-002',
    domain: 'tech',
    translations: { en: 'deployment', zh: '部署', et: 'juurutamine', ja: 'デプロイ', fr: 'déploiement', de: 'Bereitstellung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-003',
    domain: 'tech',
    translations: { en: 'middleware', zh: '中间件', et: 'vahevara', ja: 'ミドルウェア', fr: 'intergiciel', de: 'Middleware' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-004',
    domain: 'tech',
    translations: { en: 'algorithm', zh: '算法', et: 'algoritm', ja: 'アルゴリズム', fr: 'algorithme', de: 'Algorithmus' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-005',
    domain: 'tech',
    translations: { en: 'authentication', zh: '认证', et: 'autentimine', ja: '認証', fr: 'authentification', de: 'Authentifizierung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-006',
    domain: 'tech',
    translations: { en: 'backend', zh: '后端', et: 'taustarakendus', ja: 'バックエンド', fr: 'back-end', de: 'Backend' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-007',
    domain: 'tech',
    translations: { en: 'frontend', zh: '前端', et: 'kasutajaliides', ja: 'フロントエンド', fr: 'front-end', de: 'Frontend' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-008',
    domain: 'tech',
    translations: { en: 'cache', zh: '缓存', et: 'vahemälu', ja: 'キャッシュ', fr: 'cache', de: 'Cache' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-009',
    domain: 'tech',
    translations: { en: 'database', zh: '数据库', et: 'andmebaas', ja: 'データベース', fr: 'base de données', de: 'Datenbank' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-010',
    domain: 'tech',
    translations: { en: 'encryption', zh: '加密', et: 'krüptimine', ja: '暗号化', fr: 'chiffrement', de: 'Verschlüsselung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-011',
    domain: 'tech',
    translations: { en: 'framework', zh: '框架', et: 'raamistik', ja: 'フレームワーク', fr: 'framework', de: 'Framework' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-012',
    domain: 'tech',
    translations: { en: 'latency', zh: '延迟', et: 'latentsus', ja: 'レイテンシ', fr: 'latence', de: 'Latenz' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-013',
    domain: 'tech',
    translations: { en: 'microservice', zh: '微服务', et: 'mikroteenus', ja: 'マイクロサービス', fr: 'microservice', de: 'Microservice' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-014',
    domain: 'tech',
    translations: { en: 'refactoring', zh: '重构', et: 'refaktoreerimine', ja: 'リファクタリング', fr: 'refactorisation', de: 'Refactoring' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-015',
    domain: 'tech',
    translations: { en: 'repository', zh: '仓库', et: 'hoidla', ja: 'リポジトリ', fr: 'dépôt', de: 'Repository' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-016',
    domain: 'tech',
    translations: { en: 'runtime', zh: '运行时', et: 'käitusaeg', ja: 'ランタイム', fr: 'environnement d\'exécution', de: 'Laufzeit' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-017',
    domain: 'tech',
    translations: { en: 'scalability', zh: '可扩展性', et: 'skaleeritavus', ja: 'スケーラビリティ', fr: 'évolutivité', de: 'Skalierbarkeit' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-018',
    domain: 'tech',
    translations: { en: 'throughput', zh: '吞吐量', et: 'läbilaskevõime', ja: 'スループット', fr: 'débit', de: 'Durchsatz' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-019',
    domain: 'tech',
    translations: { en: 'containerization', zh: '容器化', et: 'konteineriseerimine', ja: 'コンテナ化', fr: 'conteneurisation', de: 'Containerisierung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-020',
    domain: 'tech',
    translations: { en: 'continuous integration', zh: '持续集成', et: 'pidev integratsioon', ja: '継続的インテグレーション', fr: 'intégration continue', de: 'kontinuierliche Integration' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-021',
    domain: 'tech',
    translations: { en: 'load balancing', zh: '负载均衡', et: 'koormuse tasakaalustamine', ja: 'ロードバランシング', fr: 'répartition de charge', de: 'Lastverteilung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-022',
    domain: 'tech',
    translations: { en: 'version control', zh: '版本控制', et: 'versioonihaldus', ja: 'バージョン管理', fr: 'gestion de versions', de: 'Versionsverwaltung' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-023',
    domain: 'tech',
    translations: { en: 'cloud computing', zh: '云计算', et: 'pilvandmetöötlus', ja: 'クラウドコンピューティング', fr: 'informatique en nuage', de: 'Cloud-Computing' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-024',
    domain: 'tech',
    translations: { en: 'machine learning', zh: '机器学习', et: 'masinõpe', ja: '機械学習', fr: 'apprentissage automatique', de: 'maschinelles Lernen' },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'preset-tech-025',
    domain: 'tech',
    translations: { en: 'open source', zh: '开源', et: 'avatud lähtekood', ja: 'オープンソース', fr: 'open source', de: 'Open Source' },
    createdAt: 0,
    updatedAt: 0,
  },
];

export const PRESET_TERMS: Record<string, Term[]> = {
  'terms:general': PRESET_TERMS_GENERAL,
  'terms:legal': PRESET_TERMS_LEGAL,
  'terms:medical': PRESET_TERMS_MEDICAL,
  'terms:tech': PRESET_TERMS_TECH,
};
